#!/usr/bin/env python
import sys
import cv2
import numpy
import theodoimage

if __name__ == "__main__":

    input_filename = sys.argv[1]
    source = cv2.imread(input_filename)

    merged  = theodoimage.appendGreyAndColorVersions(source)

    if len(sys.argv) > 2:
        output_filename = sys.argv[2]
    else:
        output_filename = 'greycolor_' + input_filename

    cv2.imwrite(output_filename, merged)
